INSERT INTO MNET (
    ID,
    SHORTNAME,
    LONGNAME,
    URL,
    MNETTYPE_ID,
    MWOBTAIN,
    ACQMETHOD,
    MADIS,
    CATEGORY,
    LAST_CHANGED,
    PERIOD_CHECKED,
    MADIS_CATEGORY,
    RESTRICTED_DATA,
    RESTRICTED_METADATA,
    CITATION,
    PROGRAM
) VALUES (
    0,                         
    'WSV',                      
    'Germany WSV/Pegelonline (Federal Waterways and Shipping Administration)',
    'https://www.pegelonline.wsv.de/',
    NULL,                       
    'DIRECT',                   
    'API',                      
    NULL,                       
    14,                         
    NOW(),                      
    15,                         
    3,                         
    0,                         
    0,                         
    'Data provided by the Federal Waterways and Shipping Administration (WSV) of Germany via the PEGELONLINE service, licensed under DL-DE->Zero-2.0.', NULL                        
);